#!/bin/sh
export PYTHONPATH=${PYTHONPATH}:${PWD}
export FLASK_APP=hive
export FLASK_ENV=development
scss hive/scss/main.scss hive/static/css/main.css
npx webpack
flask db upgrade
echo "END DATABASE MIGRATIONS\nSTARTING HIVE..."
flask run -p 8080
