#!/bin/sh
export PYTHONPATH=${PYTHONPATH}:${PWD}
export FLASK_APP=wsgi:app
export FLASK_ENV=production

flask db upgrade
kill `cat twistd.pid` || true
rm twistd.pid || true
twistd -n web --listen tcp:8080 --wsgi wsgi.app
